### ISSUE TITLE
.exe file won't run

### ISSUE THREAD

**Issue by swifteagle303** [NicolausWolfrum/CSCI2270FinalProject#1]
When attempting to install as instructed I received a system error on the computer lab windows machine. System error: The program cannot start because MSVCP120D.dll is missing from your computer. The 2 PC computers I tested on displayed this issue. It is probably an issue concerning a windows runtime library but it might be worth noting in your read me.

**Comment by 585gabe** [comment]
I get the same error as well on my windows laptop. Additionally, the .exe will not run on the VM either from the terminal nor just double clicking on it. How did you guys create the .exe file? Most likely there was a file that was not added to it.

**Comment by trsteve** [comment]
I got the same error. I think the .exe file is the compiled file from CodeBlock somehow. I just wonder could you guys build a project in CodeBlock and add the folder to github? I think this will be easier to access. Or I'll just try do it myself. :)
