### ISSUE TITLE
User can ask for cards that are not in users hand

### ISSUE THREAD

**Issue by swifteagle303** [NicolausWolfrum/CSCI2270FinalProject#3]
No error here but I recall in the readMe file you mentioned that the program should check that the user has that card in their hand before they ask for it. When running the program the user can ask for a 7 and receive 7s even if a 7 was not originally in his or her hand. I believe in GoFish you should have that card in your hand before you ask for it but feel free to correct me if I am wrong.

**Comment by 585gabe** [comment]
You are correct according to the official go fish rules (never thought I would ever type that!)
http://www.bicyclecards.com/card-games/rule/go-fish
