### ISSUE TITLE
Other suggestions

### ISSUE THREAD

**Issue by swifteagle303** [NicolausWolfrum/CSCI2270FinalProject#4]
Solid program overall with no errors I could find. There are a couple things that could be added on top of the things mentioned in your readMe to make the program more efficient. When the player pushes 4 you print all the options he or she can ask for. That print line could be formatted to be slightly more readable since CodeBlocks and terminal typically appears as a small window. When finding cards it would be a nice feature if the user knew how many he or she acquired. That way the user does not have to consistently push 3. You could also add a way to see what books have been made for user connivence. Lastly you could allow the player to enter their name to more or less make the program more personal instead of the user being referred to as player 1. This could also be implemented with player vs player if you add that in the future.

**Comment by 585gabe** [comment]
Likewise, no matter what I did, I could get no errors or anomalies while running the program. A rarity considering the state of most of the other projects. Good job! :+1:
